word_manage_app/urls.py
from django.urls import path

from . import views

app_name = 'word_manage_app'
# このapp_nameは何の為？

urlpatterns = [
    path('index', views.index, name='index'),
    path('staticTest', views.staticTest, name = 'staticTest'),
    path('onclickTest', views.onclickTest, name = 'onclickTest'),
    path('<int:word_id>/detail', views.detail, name = 'detail'),

]

word_manage_project/urls.py
from django.conf.urls import url, include
from django.urls import path
from django.contrib import admin


urlpatterns = [
	path('index/', include('word_manage_app.urls')),
    path('word_manage_app/', include('word_manage_app.urls')),
    url(r'^admin/', admin.site.urls),
    
]

word_manage_app/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Reference(models.Model):
	reference = models.CharField(max_length=128, default = "english text reference.")
	# referenceにdefaultの引数がないとpython3 manage.py makemigrationsするとエラーが起きる

	def __str__(self):
		return self.reference[:20]


class Word(models.Model): #この時のmodelsはファイル名？Modelはクラス名?
	new_word = models.CharField('新しいワード', max_length=128)
	# 「新しい言葉」という引数を渡すと表記が「new_word」から「新しい言葉」に変わる
	meaning = models.TextField()
	# reference = models.ManyToManyField(Reference)
	reference = models.ForeignKey(Reference, null=True, on_delete=models.PROTECT)
	# verbose_name="参照"
	"""
	example = models.TextField(verbose_name = "例文")
	後から付け加えようとするとエラーが出る
	"""
	note = models.TextField()
	first_date = models.DateTimeField('first day registering this word.')
	access = models.IntegerField(default = 0, editable = False)
	
	def __str__(self):
		return self.new_word
	
class Expression(models.Model):
	expression = models.CharField(max_length=128)
	meaning = models.TextField()
	reference = models.ManyToManyField(Reference)
	note = models.TextField()

	def __str__(self):
		return self.expression

word_manage_app/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.
from .models import Word

from django.http import HttpResponse
from django.template import loader
from django.http import Http404



def index(request):
	word_list = Word.objects.all()
	"""
	output = '¥n, '.join([w.meaning for w in word_list])
	"""
	template = loader.get_template('word_manage_app/index.html')
	
	context = {
		'word_list' : word_list,
	}

	return HttpResponse(template.render(context, request))

def staticTest(request):

	template = loader.get_template('word_manage_app/staticTest.html')
	context = {}
	
	return HttpResponse(template.render(context, request))


def onclickTest(request):

	template = loader.get_template('word_manage_app/onclickTest.html')
	context = {}
	
	return HttpResponse(template.render(context, request))


def detail(request, word_id):
	"try,exceptの中身はget_object_or_404(Word, pk=word_id)で補えるが、理解の為に以下のように書く"
	try:
		word = Word.objects.get(pk = word_id)

	except Word.DoesNotExist:
		raise Http404("Word does not exist")

	context = {'word' : word}
	return render(request, 'word_manage_app/detail.html', context)

word_manage_app/templates/word_manage_app/detail.html
<!DOCTYPE html>
<html>
<body>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}


<h1>{{ word.new_word }}</h1>
<li>{{word.meaning}}</li>
<li>{{word.reference}}</li>
<li>{{word.note}}</li>
<li>{{word.access}}回</li>

<div>
	<input type="checkbox" name="reference">{{word.reference}}</input>
	<input type="checkbox" name="reference">{{word.reference}}</input>
<div>

<br><br>
<time>First Date: {{word.first_date}}</time>

</html>
</body>

word_manage_app/templates/word_manage_app/index.html
<!DOCTYPE html>

{% load static %}

<html lang=en >

<head>
    <link rel="stylesheet" type="text/css" href="{% static 'word_manage_app/style.css' %}">
    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js">
    </script>
    </script>

    <script src="{% static 'word_manage_app/app.js'%}"></script>
    <script src="{% static 'word_manage_app/tab.js'%}"></script>
    <script src="{% static 'word_manage_app/tab2.js'%}"></script>

    
    <title>Index page</title>
    
</head>


<header>
   <div id = "header1" >User is: {{user}}</div> <br>
</header>

<body>
    

    <script>
        console.log("{% static 'word_manage_app/tab.js'%}");

        console.log(window);
    </script>

    <div class="tab_wrap">
        <div class="tab_area">
            <label class="tab1_label" for="panel1">tab1</label>
            <label class="tab2_label" for="panel2">tab2</label>
        </div>

        <div class="panel_area">
            <div id="panel1" class="tab_panel">
                <p>panel1</p>
            </div>
            <div id="panel2" class="tab_panel">
                <p>panel2</p>
            </div>
        </div>
    </div>
    <button>ボタン</button><br>




    
</body>



---------------------------<br>
<footer>
    footer<br>
{% if user.is_superuser %}
<a href = "{% url 'admin:index' %}" target="_blank">admin index page</a>
{% else %}
user is not superuser

{% endif %}
</footer>

</html>
<!--
'admin:word_manage_app_word_add'でadminサイトの
ワード追加ページに移行できる
adminサイトにも逆引き出来るviewの名前があり、
アプリ名_モデル名_内容（注:内容はaddやdetailなど）で、逆引き出来る
参照:https://docs.djangoproject.com/en/2.1/ref/contrib/admin/
Reversing admin URLs

target="_blank"を付けると
-->

word_manage_app/templates/word_manage_app/index_tmp.html
{% if word_list %}
        <p>Word Exists</p>
        {% for word in word_list %}
            <article>
            	<li>ID: {{word.id}}</li>
            	<li>ForLoopID: {{ forloop.counter }}</li>
            	<li><a href="{% url 'word_manage_app:detail' word.id %}">{{ word.new_word}}</a></li>
            	
                <br>
            </article>
        	<!--
    		{% url 'word_manage_app:detail' word.id %}は
    		href="/word_manage_app/{{ word.id }/detail}
    		と同じ
        	-->    
        {% endfor %}

    {% else %}
        <p>No words are available.</p>
    {% endif %}

word_manage_app/templates/word_manage_app/onclickTest.html
<!DOCTYPE html>


{% load static %}
<html>
	<head>
		<script>
		function myFunction() {
			alert("this is onclick Test");
		}
		</script>
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
		<script src="{% static 'word_manage_app/onclickTest.js'%}"></script>
	</head>

	

	<body>
		"{% static 'word_manage_app/onclickTest.js'%}"<br>
		<button onclick="myFunction()">ボタン1</button><br>
		<button onclick="myFunction2()">ボタン2</button><br>
		<button onclick="myFunction3()" class="clickTest">P</button>
	</body>

</html>

word_manage_app/templates/word_manage_app/onlyTabs.html
<style>
.tab_wrap{width:500px; margin:80px auto;}
.tab_area{font-size:0; margin:0 10px;}
.tab_area label{width:150px; margin:0 5px; display:inline-block; padding:12px 0; color:#999; background:#ddd; text-align:center; font-size:13px; cursor:pointer; transition:ease 0.2s opacity;}

.tab_area label:hover{opacity:0.8;background-color: red;}
</style>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<script>

$("label.tab1_label").click(function(){
		console.log("tab1_label is clicked:");
	});

function myFunction2() {
	var element = document.getElementById("myDIV1");
	console.log(document.all);
	console.log(element);
	console.log(element.classList);

	var element2 = document.getElementById("myDIV2");
	console.log(element2);
	console.log(element2.classList);
}

console.log("myFunction2 is called here:");

</script>


<div class = "tab_wrap" id = "myDIV1">
	<div class="tab_area" id = "myDIV2">
		<label class="tab1_label", for="tab1", onclick="myFunction2()">tab1</label>
		<label class="tab2_label" for="tab2">tab2</label>
		<label class="tab3_label" for="tab3">tab3</label>
	</div>
</div>

word_manage_app/templates/word_manage_app/staticTest.html
<script>
    alert("this alert");
</script>

2------------from js files<br>
<script src="{% static 'word_manage_app/app.js' %}"></script><br>
{% static 'word_manage_app/app.js' %}<br>

3------------in this html<br>
<script type="text/javascript">
    

    window.open();

</script>
4------------logging
<script>
    console.log("javascript in html");
</script>

word_manage_app/templates/word_manage_app/tabOnlyWithCSS.html
<div class="tab_wrap">
	<input id="tab1" type="radio" name="tab_btn" checked>
	<input id="tab2" type="radio" name="tab_btn">
	<input id="tab3" type="radio" name="tab_btn">
 
	<div class="tab_area">
		<label class="tab1_label" for="tab1">tab1</label>
		<label class="tab2_label" for="tab2">tab2</label>
		<label class="tab3_label" for="tab3">tab3</label>
	</div>
	<div class="panel_area">
		<div id="panel1" class="tab_panel">
			<p>panel1</p>
		</div>
		<div id="panel2" class="tab_panel">
			<p>panel2</p>
		</div>
		<div id="panel3" class="tab_panel">
			<p>panel3</p>
		</div>
	</div>
</div>

word_manage_app/templates/word_manage_app/tabWithJS.html
<div class="tab_wrap">
	<div class="tab_area">
		<label class="tab1_label" for="tab1">tab1</label>
		<label class="tab2_label" for="tab2">tab2</label>
		<label class="tab3_label" for="tab3">tab3</label>
	</div>
	<div class="panel_area">
		<div id="panel1" class="tab_panel">
			<p>panel1</p>
		</div>
		<div id="panel2" class="tab_panel">
			<p>panel2</p>
		</div>
		<div id="panel3" class="tab_panel">
			<p>panel3</p>
		</div>
	</div>
</div>